# -*- coding: utf-8 -*-
"""TEXT SUMMARIZATION OF NEWS ARTICLES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_JfvX3elN6JDhGK7VqNFLmacDNxfYBZf

**CORE PROJECT - TEXT SUMMARIZATION OF NEWS ARTICLES**
"""

# WE NEED TO INSTALL THE BELOW PACKAGES

# !pip install nltk # Natural Language Toolkit
# !pip install newspaper3k # web scraping library that allows us to extract and parse news articles
# IMPORTING THE LIBRARIES

import nltk
from newspaper import Article

# ASSIGNING ANY NEWS ARTICLE URL TO A VARIABLE

url = 'https://www.hindustantimes.com/world-news/trinity-test-date-what-was-manhattan-project-oppenheimer-movie-world-war-ii-father-of-atomic-bomb-cillian-murphy-latest-101690197205297.html'
article = Article(url)

# WE DOWNLOAD THE ARTICLE AND PARSE THE ARTICLE

article.download()
article.parse()
nltk.download('punkt') # downloads the 'punkt'from the NLTK library. This is required for NLP tasks like tokenization.
article.nlp() # The 'nlp()' method is called on the 'article' object and we can extract various information, such as keywords, summary, and more.

# WE GET THE AUTHORS OF THAT ARTICLE

article.authors

# WE GET THE PUBLISHED DATE AND TIME OF THAT ARTICLE

article.publish_date

# WE GET THE TOP IMAGE OF THAT ARTICLE

article.top_image

# WE GET THE TOTAL INFORMATION OF THAT ARTICLE

print(article.text)

# FINALLY WE GET THE ARTICLE SUMMARY

print(article.summary)

